site_name: LEMMA Documentation
repo_url: "https://github.com/mkerin/LEMMA"
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - Install: install.md
  - LEMMA: lemma.md
  - GPLEMMA: gplemma.md